name: "verify"

on:
  workflow_dispatch:

jobs:
  maven-test:
    name: "maven/test"
    runs-on:
    - "ubuntu-latest"
    container:
      image: "cimg/openjdk:11.0"
    services:
      cimg/postgres:14.1:
        image: "cimg/postgres:14.1"
        env:
          POSTGRES_PASSWORD: "password"
          POSTGRES_USER: "postgres"
          POSTGRES_DB: "cfd"
    steps:
    - uses: "actions/checkout@v4"
    - 
      run: "wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz"
      name: "Install dockerize"
      env:
        DOCKERIZE_VERSION: "v0.6.1"
    - run: "dockerize -wait tcp://172.17.0.1:5432 -timeout 1m"
    - run: "mvn verify"

